In [109]:
from google.cloud import bigquery

bqclient = bigquery.Client()

# Download query results.
query_string = """
SELECT
CONCAT(
    'https://stackoverflow.com/questions/',
    CAST(id as STRING)) as url,
view_count
FROM `bigquery-public-data.stackoverflow.posts_questions`
WHERE tags like '%google-bigquery%'
ORDER BY view_count DESC
"""

dataframe = (
    bqclient.query(query_string)
    .result()
    .to_dataframe(
        # Optionally, explicitly request to use the BigQuery Storage API. As of
        # google-cloud-bigquery version 1.26.0 and above, the BigQuery Storage
        # API is used by default.
        create_bqstorage_client=True,
    )
)
print(dataframe.head())

                                            url  view_count
0  https://stackoverflow.com/questions/35159967      110426
1  https://stackoverflow.com/questions/22879669      104978
2  https://stackoverflow.com/questions/10604135      100158
3  https://stackoverflow.com/questions/27060396       84098
4  https://stackoverflow.com/questions/11057219       76822

In [110]:
query_string = """
SELECT
   COUNT(*)
 FROM `bigquery-public-data.epa_historical_air_quality.co_daily_summary`
 """
dataframe = (
    bqclient.query(query_string)
    .result()
    .to_dataframe(
        # Optionally, explicitly request to use the BigQuery Storage API. As of
        # google-cloud-bigquery version 1.26.0 and above, the BigQuery Storage
        # API is used by default.
        create_bqstorage_client=True,
    )
)
print(dataframe.head())

       f0_
0  8614411

In [111]:
'''your_project_id = "carbon-score-cmpe272"
from google.cloud import bigquery_storage
from google.cloud.bigquery_storage import types
import pandas

bqstorageclient = bigquery_storage.BigQueryReadClient()

project_id = "bigquery-public-data"
dataset_id = "epa_historical_air_quality"
table_id = "co_daily_summary"
table = f"projects/{project_id}/datasets/{dataset_id}/tables/{table_id}"

# If no read options are specified, the whole table is read.
read_options = types.ReadSession.TableReadOptions(
    row_restriction='Row BETWEEN 1 AND 10')

parent = "projects/{}".format(your_project_id)

requested_session = types.ReadSession(
    table=table,
    # Avro is also supported, but the Arrow data format is optimized to
    # work well with column-oriented data structures such as pandas
    # DataFrames.
    data_format=types.DataFormat.ARROW,
    read_options=read_options,
)
read_session = bqstorageclient.create_read_session(
    parent=parent, read_session=requested_session, max_stream_count=1,
)

# This example reads from only a single stream. Read from multiple streams
# to fetch data faster. Note that the session may not contain any streams
# if there are no rows to read.
stream = read_session.streams[0]
reader = bqstorageclient.read_rows(stream.name)

# Parse all Arrow blocks and create a dataframe.
frames = []
for message in reader.rows().pages:
    frames.append(message.to_dataframe())
dataframe = pandas.concat(frames)
print(dataframe.head())'''

'your_project_id = "carbon-score-cmpe272"\nfrom google.cloud import bigquery_storage\nfrom google.cloud.bigquery_storage import types\nimport pandas\n\nbqstorageclient = bigquery_storage.BigQueryReadClient()\n\nproject_id = "bigquery-public-data"\ndataset_id = "epa_historical_air_quality"\ntable_id = "co_daily_summary"\ntable = f"projects/{project_id}/datasets/{dataset_id}/tables/{table_id}"\n\n# If no read options are specified, the whole table is read.\nread_options = types.ReadSession.TableReadOptions(\n    row_restriction=\'Row BETWEEN 1 AND 10\')\n\nparent = "projects/{}".format(your_project_id)\n\nrequested_session = types.ReadSession(\n    table=table,\n    # Avro is also supported, but the Arrow data format is optimized to\n    # work well with column-oriented data structures such as pandas\n    # DataFrames.\n    data_format=types.DataFormat.ARROW,\n    read_options=read_options,\n)\nread_session = bqstorageclient.create_read_session(\n    parent=parent, read_session=requested_session, max_stream_count=1,\n)\n\n# This example reads from only a single stream. Read from multiple streams\n# to fetch data faster. Note that the session may not contain any streams\n# if there are no rows to read.\nstream = read_session.streams[0]\nreader = bqstorageclient.read_rows(stream.name)\n\n# Parse all Arrow blocks and create a dataframe.\nframes = []\nfor message in reader.rows().pages:\n    frames.append(message.to_dataframe())\ndataframe = pandas.concat(frames)\nprint(dataframe.head())'

In [112]:
'''query_string = """
SELECT * FROM bigquery-public-data.epa_historical_air_quality.co_daily_summary
LIMIT 10
"""

query_string2 = """
SELECT * FROM bigquery-public-data.epa_historical_air_quality.co_daily_summary
WHERE ROWNUM <= 3
"""

# RowNumber
# WHERE Row BETWEEN 1 AND 10

dataframe = (
    bqclient.query(query_string)
    .result()
    .to_dataframe(
        # Optionally, explicitly request to use the BigQuery Storage API. As of
        # google-cloud-bigquery version 1.26.0 and above, the BigQuery Storage
        # API is used by default.
        create_bqstorage_client=True,
    )
)
print(len(dataframe))
print(dataframe)'''

'query_string = """\nSELECT * FROM bigquery-public-data.epa_historical_air_quality.co_daily_summary\nLIMIT 10\n"""\n\nquery_string2 = """\nSELECT * FROM bigquery-public-data.epa_historical_air_quality.co_daily_summary\nWHERE ROWNUM <= 3\n"""\n\n# RowNumber\n# WHERE Row BETWEEN 1 AND 10\n\ndataframe = (\n    bqclient.query(query_string)\n    .result()\n    .to_dataframe(\n        # Optionally, explicitly request to use the BigQuery Storage API. As of\n        # google-cloud-bigquery version 1.26.0 and above, the BigQuery Storage\n        # API is used by default.\n        create_bqstorage_client=True,\n    )\n)\nprint(len(dataframe))\nprint(dataframe)'

In [113]:
rows = bqclient.list_rows(table_path, max_results=10)
dataframe = rows.to_dataframe(create_bqstorage_client=True,)
print(dataframe.head())

  state_code county_code site_num  parameter_code  poc   latitude  longitude  \
0         02         020     0050           42101    1  61.115000 -149.84610
1         04         027     8011           42101    1  32.690278 -114.61444
2         04         027     8011           42101    1  32.690278 -114.61444
3         08         067     7001           42101    1  37.136780 -107.62863
4         08         067     7001           42101    1  37.136780 -107.62863

   datum   parameter_name        sample_duration  ...  aqi method_code  \
0  WGS84  Carbon monoxide  8-HR RUN AVG END HOUR  ...  9.0         NaN
1  WGS84  Carbon monoxide                 1 HOUR  ...  NaN        54.0
2  WGS84  Carbon monoxide                 1 HOUR  ...  NaN        54.0
3  WGS84  Carbon monoxide                 1 HOUR  ...  NaN        54.0
4  WGS84  Carbon monoxide                 1 HOUR  ...  NaN        54.0

                             method_name local_site_name  \
0                                      -   BOWMAN SCHOOL
1  INSTRUMENTAL - NONDISPERSIVE INFRARED  YUMA SUPERSITE
2  INSTRUMENTAL - NONDISPERSIVE INFRARED  YUMA SUPERSITE
3  INSTRUMENTAL - NONDISPERSIVE INFRARED           UTE 1
4  INSTRUMENTAL - NONDISPERSIVE INFRARED           UTE 1

                                 address  state_name  county_name  \
0                       11700 GREGORY RD      Alaska   Anchorage
1                     2323 S ARIZONA AVE     Arizona         Yuma
2                     2323 S ARIZONA AVE     Arizona         Yuma
3  1 MI. NE OF IGNACIO ON COUNTY RD. 517    Colorado     La Plata
4  1 MI. NE OF IGNACIO ON COUNTY RD. 517    Colorado     La Plata

       city_name      cbsa_name  date_of_last_change
0      Anchorage  Anchorage, AK           2016-04-12
1           Yuma       Yuma, AZ           2021-04-09
2           Yuma       Yuma, AZ           2021-04-09
3  Not in a city    Durango, CO           2016-04-12
4  Not in a city    Durango, CO           2016-04-12

[5 rows x 29 columns]

In [114]:
len(dataframe)

10

In [115]:
rows = bqclient.list_rows(table_path, max_results=108)
df = rows.to_dataframe(create_bqstorage_client=True,)
len(df)
print(df.head())

  state_code county_code site_num  parameter_code  poc   latitude  longitude  \
0         02         020     0050           42101    1  61.115000 -149.84610
1         04         027     8011           42101    1  32.690278 -114.61444
2         04         027     8011           42101    1  32.690278 -114.61444
3         08         067     7001           42101    1  37.136780 -107.62863
4         08         067     7001           42101    1  37.136780 -107.62863

   datum   parameter_name        sample_duration  ...  aqi method_code  \
0  WGS84  Carbon monoxide  8-HR RUN AVG END HOUR  ...  9.0         NaN
1  WGS84  Carbon monoxide                 1 HOUR  ...  NaN        54.0
2  WGS84  Carbon monoxide                 1 HOUR  ...  NaN        54.0
3  WGS84  Carbon monoxide                 1 HOUR  ...  NaN        54.0
4  WGS84  Carbon monoxide                 1 HOUR  ...  NaN        54.0

                             method_name local_site_name  \
0                                      -   BOWMAN SCHOOL
1  INSTRUMENTAL - NONDISPERSIVE INFRARED  YUMA SUPERSITE
2  INSTRUMENTAL - NONDISPERSIVE INFRARED  YUMA SUPERSITE
3  INSTRUMENTAL - NONDISPERSIVE INFRARED           UTE 1
4  INSTRUMENTAL - NONDISPERSIVE INFRARED           UTE 1

                                 address  state_name  county_name  \
0                       11700 GREGORY RD      Alaska   Anchorage
1                     2323 S ARIZONA AVE     Arizona         Yuma
2                     2323 S ARIZONA AVE     Arizona         Yuma
3  1 MI. NE OF IGNACIO ON COUNTY RD. 517    Colorado     La Plata
4  1 MI. NE OF IGNACIO ON COUNTY RD. 517    Colorado     La Plata

       city_name      cbsa_name  date_of_last_change
0      Anchorage  Anchorage, AK           2016-04-12
1           Yuma       Yuma, AZ           2021-04-09
2           Yuma       Yuma, AZ           2021-04-09
3  Not in a city    Durango, CO           2016-04-12
4  Not in a city    Durango, CO           2016-04-12

[5 rows x 29 columns]

In [116]:
df

,state_code,county_code,site_num,parameter_code,poc,latitude,longitude,datum,parameter_name,sample_duration,...,aqi,method_code,method_name,local_site_name,address,state_name,county_name,city_name,cbsa_name,date_of_last_change
0,02,020,0050,42101,1,61.115000,-149.846100,WGS84,Carbon monoxide,8-HR RUN AVG END HOUR,...,9.0,NaN,-,BOWMAN SCHOOL,11700 GREGORY RD,Alaska,Anchorage,Anchorage,"Anchorage, AK",2016-04-12
1,04,027,8011,42101,1,32.690278,-114.614440,WGS84,Carbon monoxide,1 HOUR,...,NaN,54.0,INSTRUMENTAL - NONDISPERSIVE INFRARED,YUMA SUPERSITE,2323 S ARIZONA AVE,Arizona,Yuma,Yuma,"Yuma, AZ",2021-04-09
2,04,027,8011,42101,1,32.690278,-114.614440,WGS84,Carbon monoxide,1 HOUR,...,NaN,54.0,INSTRUMENTAL - NONDISPERSIVE INFRARED,YUMA SUPERSITE,2323 S ARIZONA AVE,Arizona,Yuma,Yuma,"Yuma, AZ",2021-04-09
3,08,067,7001,42101,1,37.136780,-107.628630,WGS84,Carbon monoxide,1 HOUR,...,NaN,54.0,INSTRUMENTAL - NONDISPERSIVE INFRARED,UTE 1,1 MI. NE OF IGNACIO ON COUNTY RD. 517,Colorado,La Plata,Not in a city,"Durango, CO",2016-04-12
4,08,067,7001,42101,1,37.136780,-107.628630,WGS84,Carbon monoxide,1 HOUR,...,NaN,54.0,INSTRUMENTAL - NONDISPERSIVE INFRARED,UTE 1,1 MI. NE OF IGNACIO ON COUNTY RD. 517,Colorado,La Plata,Not in a city,"Durango, CO",2016-04-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,40,143,0191,42101,1,36.141697,-95.983793,WGS84,Carbon monoxide,8-HR RUN AVG END HOUR,...,76.0,NaN,-,CINCINNATI,"1413 S. CINCINNATI, TULSA, OK 74119",Oklahoma,Tulsa,Tulsa,"Tulsa, OK",2016-04-22
104,40,143,0191,42101,1,36.141697,-95.983793,WGS84,Carbon monoxide,8-HR RUN AVG END HOUR,...,10.0,NaN,-,CINCINNATI,"1413 S. CINCINNATI, TULSA, OK 74119",Oklahoma,Tulsa,Tulsa,"Tulsa, OK",2016-04-22
105,41,039,2062,42101,1,44.045640,-123.082217,WGS84,Carbon monoxide,1 HOUR,...,NaN,66.0,INSTRUMENTAL - NONDISPERSIVE INFRARED,None,"SACRED HEART HOSP./1255 HILYARD, EUGENE",Oregon,Lane,Eugene,"Eugene, OR",2016-04-22
106,41,039,2062,42101,1,44.045640,-123.082217,WGS84,Carbon monoxide,1 HOUR,...,NaN,66.0,INSTRUMENTAL - NONDISPERSIVE INFRARED,None,"SACRED HEART HOSP./1255 HILYARD, EUGENE",Oregon,Lane,Eugene,"Eugene, OR",2016-04-22
107,41,047,0039,42101,1,44.950120,-122.984262,WGS84,Carbon monoxide,8-HR RUN AVG END HOUR,...,18.0,NaN,-,None,"1685 LANCASTER DR. NE, SALEM, OR",Oregon,Marion,Salem,"Salem, OR",2018-06-05

In [117]:
df['date_local']

0      2006-02-11
1      2006-07-22
2      2006-08-09
3      2006-01-10
4      2006-12-25
          ...
103    1997-01-31
104    1997-11-25
105    1997-05-29
106    1997-12-11
107    1997-10-05
Name: date_local, Length: 108, dtype: object

In [118]:
import pandas as pd
df['date_local'] = pd.to_datetime(df['date_local'], infer_datetime_format=True)
#df.sort_values(by=['date_local'])
#df.sort_values(by='date_local')
print(df.head())

  state_code county_code site_num  parameter_code  poc   latitude  longitude  \
0         02         020     0050           42101    1  61.115000 -149.84610
1         04         027     8011           42101    1  32.690278 -114.61444
2         04         027     8011           42101    1  32.690278 -114.61444
3         08         067     7001           42101    1  37.136780 -107.62863
4         08         067     7001           42101    1  37.136780 -107.62863

   datum   parameter_name        sample_duration  ...  aqi method_code  \
0  WGS84  Carbon monoxide  8-HR RUN AVG END HOUR  ...  9.0         NaN
1  WGS84  Carbon monoxide                 1 HOUR  ...  NaN        54.0
2  WGS84  Carbon monoxide                 1 HOUR  ...  NaN        54.0
3  WGS84  Carbon monoxide                 1 HOUR  ...  NaN        54.0
4  WGS84  Carbon monoxide                 1 HOUR  ...  NaN        54.0

                             method_name local_site_name  \
0                                      -   BOWMAN SCHOOL
1  INSTRUMENTAL - NONDISPERSIVE INFRARED  YUMA SUPERSITE
2  INSTRUMENTAL - NONDISPERSIVE INFRARED  YUMA SUPERSITE
3  INSTRUMENTAL - NONDISPERSIVE INFRARED           UTE 1
4  INSTRUMENTAL - NONDISPERSIVE INFRARED           UTE 1

                                 address  state_name  county_name  \
0                       11700 GREGORY RD      Alaska   Anchorage
1                     2323 S ARIZONA AVE     Arizona         Yuma
2                     2323 S ARIZONA AVE     Arizona         Yuma
3  1 MI. NE OF IGNACIO ON COUNTY RD. 517    Colorado     La Plata
4  1 MI. NE OF IGNACIO ON COUNTY RD. 517    Colorado     La Plata

       city_name      cbsa_name  date_of_last_change
0      Anchorage  Anchorage, AK           2016-04-12
1           Yuma       Yuma, AZ           2021-04-09
2           Yuma       Yuma, AZ           2021-04-09
3  Not in a city    Durango, CO           2016-04-12
4  Not in a city    Durango, CO           2016-04-12

[5 rows x 29 columns]

In [119]:
df = df.sort_values(by='date_local')
df['date_local']

93   1997-01-03
86   1997-01-04
94   1997-01-07
62   1997-01-24
67   1997-01-25
        ...
17   2006-12-22
8    2006-12-24
4    2006-12-25
41   2006-12-30
56   2006-12-30
Name: date_local, Length: 108, dtype: datetime64[ns]

In [120]:
print(df.head())

   state_code county_code site_num  parameter_code  poc   latitude  longitude  \
93         37         067     0026           42101    1  36.067500 -80.293889
86         33         011     1009           42101    1  42.764532 -71.467010
94         37         067     0026           42101    1  36.067500 -80.293889
62         17         143     0036           42101    1  40.700072 -89.613414
67         25         013     2007           42101    1  42.100650 -72.591200

    datum   parameter_name        sample_duration  ...   aqi method_code  \
93  WGS84  Carbon monoxide  8-HR RUN AVG END HOUR  ...  13.0         NaN
86  WGS84  Carbon monoxide  8-HR RUN AVG END HOUR  ...  32.0         NaN
94  WGS84  Carbon monoxide  8-HR RUN AVG END HOUR  ...   6.0         NaN
62  WGS84  Carbon monoxide                 1 HOUR  ...   NaN        54.0
67  WGS84  Carbon monoxide                 1 HOUR  ...   NaN        67.0

                              method_name                 local_site_name  \
93                                      -  BOLTON PARK EAST OF HANES MALL
86                                      -                            None
94                                      -  BOLTON PARK EAST OF HANES MALL
62  INSTRUMENTAL - NONDISPERSIVE INFRARED             COMMERCIAL BUILDING
67  INSTRUMENTAL - NONDISPERSIVE INFRARED                            None

                               address      state_name   county_name  \
93                  1590 BOLTON STREET  North Carolina       Forsyth
86  25 MAIN STREET, MATARAZZO BUILDING   New Hampshire  Hillsborough
94                  1590 BOLTON STREET  North Carolina       Forsyth
62                  1005 N. UNIVERSITY        Illinois        Peoria
67                EAST COLUMBUS AVENUE   Massachusetts       Hampden

        city_name              cbsa_name  date_of_last_change
93  Winston-Salem      Winston-Salem, NC           2016-04-22
86         Nashua  Manchester-Nashua, NH           2016-04-22
94  Winston-Salem      Winston-Salem, NC           2016-04-22
62         Peoria             Peoria, IL           2016-04-16
67    Springfield        Springfield, MA           2016-04-22

[5 rows x 29 columns]